#!/bin/sh

db='/usr/local/falco/db/cvedb'

echo "testing -t, type output, -t text:"
../falco -t text -d $db -n openssl -i 2
if [ "$?" -gt 0 ]
then
    echo "format test: failed -t text test"
    exit 1
else:
    echo "format test: passed -t text test"
fi

echo "testing -t, type output, -t json:"
../falco -t json -d $db -n python -i 2
if [ "$?" -gt 0 ]
then
    echo "format test: failed -t json test"
    exit 1
else:
    echo "format test: passed -t json test"
fi

echo "testing -t, type output, -t html:"
../falco -t html -d $db -n python -i 2
if [ "$?" -gt 0 ]
then
    echo "format test: failed -t html test"
    exit 1
else:
    echo "format test: passed -t html test"
fi

